version: '2'
services:
  db-hermess:
    image: postgres:11
    user: root
    environment:
      - POSTGRES_PASSWORD=Welcome02$$
      - POSTGRES_USER=ics
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  hermess:
    image: odoo:13
    user: root
    depends_on:
      - db-hermess
    ports:
      - "15213:8069"
      - "25213:8072" # live chat
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/test_module
    environment:
      - HOST=db-hermess
      - USER=ics
      - PASSWORD=Welcome02$$
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
